version: 2.0.{build}
image: Visual Studio 2022

before_build:
 - cmd: nuget restore src\GodaddyWrapper.sln
 
build:
  verbosity: minimal

artifacts:
  - path: '**\*.*nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - master
     
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: d6j0MYClUTLLg2QiYeQVhiU7akN9KHHt/OqOo+W+Hk2pVkH2mtp/KtsHU3etNT4k
   skip_symbols: false
   artifact: /*.*nupkg/
